# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: InvisibleNemo Project Blog 
name: "Debanjan Paul"
email: dpaul@invisiblenemo.com
repository: "InvisibleNemo/invisiblenemo.github.io"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://invisiblenemo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: InvisibleNemo
github_username:  invisiblenemo

author:
  name   : "Debanjan Paul"
  avatar : "/assets/images/DP.jpg"
  bio    : "A novice data scientist learning, and hoping to help others along the way"
  email  : "dpaul@invisiblenemo.com"
  uri    :  # "http://your-site.com"
  twitter : "https://twitter.com/invisiblenemo"
  facebook: "https://facebook.com/invisiblenemo"
  instagram: "https://instagram.com/invisiblenemo"
  linkedin: "https://www.linkedin.com/in/debanjan-paul"


social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/invisiblenemo"
    - "https://facebook.com/invisiblenemo"
    - "https://instagram.com/invisiblenemo"
    - "https://www.linkedin.com/in/debanjan-paul"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll 
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed

breadcrumbs: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

search: true

include:
  ["_pages","_posts"]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
